### Verbo GET – listar todos
GET http://127.0.0.1:8000/produto/

### Verbo GET – listar um
GET http://127.0.0.1:8000/produto/1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/
Content-Type: application/json

{
  "nome": "Pastel de frango",
  "descricao": "Pastel recheado de frango",
  "foto": "foto.jpg",
  "valor_unitario": 15.50
}

### Verbo PUT – atualizar
PUT http://127.0.0.1:8000/produto/1
Content-Type: application/json

{
  "nome": "Pastel de Frango",
  "descricao": "Pastel recheado de frango",
  "foto": "foto2.jpg",
  "valor_unitario": 17.00
}

### Verbo DELETE – remover
DELETE http://127.0.0.1:8000/produto/1